version: '3.9'
services: 
  redis: 
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports: 
      - '6379:6379'
    volumes: 
      - ./docker-volumes/cache:/data


  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports: 
      - '27017:27017'
    volumes: 
      - ./docker-volumes/data:/data/db